apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: mssql
type: Opaque
data:
  MSSQL_SA_PASSWORD: 'WXJ5NGszeCEzNjQ4YWgyNGE='
  MSSQL_TLS_CERT: 'L3Zhci9vcHQvbXNzcWwvdGxzL3Rscy5jcnQ='
  MSSQL_TLS_KEY: 'L3Zhci9vcHQvbXNzcWwvdGxzL3Rscy5rZXk='
