apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mssql-certificate
  namespace: mssql
spec:
  secretName: mssql-cert
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  commonName: MSSQL Server
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
