apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-server-conf
  namespace: mssql
data:
  mssql.conf: |-
    [network]
    tlscert = /var/opt/mssql/tls/tls.crt
    tlskey = /var/opt/mssql/tls/tls.key

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mssql-account
  namespace : mssql
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: mssql
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 999
      containers:
      - name: mssql
        image: mssql:2022-latest
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nc -z localhost 1433
          initialDelaySeconds: 250
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost 1433
          initialDelaySeconds: 250
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: '1.5G'
            cpu: '1000m'
          limits:
            memory: '1.5G'
            cpu: '1000m'
        volumeMounts:
           - name: mssqldb-data
             mountPath: '/var/opt/mssql/data'
           - name: mssqldb-log
             mountPath: '/var/opt/mssql/log'
           - name: mssqldb-backup
             mountPath: '/var/opt/mssql/backup'
           - name: mssql-server-conf
             mountPath: /var/opt/mssql/mssql.conf
             subPath: mssql.conf
           - name: mssql-tls
             mountPath: '/var/opt/mssql/tls'
        ports:
        - containerPort: 1433
          protocol: TCP
        env:
        - name: ACCEPT_EULA
          value: 'Y'
        - name: MSSQL_PID
          valueFrom:
              configMapKeyRef:
                name: mssql-conf
                key: MSSQL_PID
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: MSSQL_SA_PASSWORD
        - name: LANG
          valueFrom:
              configMapKeyRef:
                name: mssql-conf
                key: LANG
        - name: LANGUAGE
          valueFrom:
              configMapKeyRef:
                name: mssql-conf
                key: LANGUAGE
        - name: LC_ALL
          valueFrom:
              configMapKeyRef:
                name: mssql-conf
                key: LC_ALL
        - name: TZ
          valueFrom:
              configMapKeyRef:
                name: mssql-conf
                key: TZ
        - name: CONFIG_EDGE_BUILD
          valueFrom:
              configMapKeyRef:
                name: mssql-conf
                key: MSSQL_EDGE_BUILD
      volumes:
        - name: mssqldb-data
          hostPath:
            path: '/run/desktop/mnt/host/c/My Databases/MSSQL/data'
            type: DirectoryOrCreate
        - name: mssqldb-log
          hostPath:
            path: '/run/desktop/mnt/host/c/My Databases/MSSQL/log'
            type: DirectoryOrCreate
        - name: mssqldb-backup
          hostPath:
            path: '/run/desktop/mnt/host/c/My Databases/MSSQL/backup'
            type: DirectoryOrCreate
        - name: mssql-server-conf
          configMap:
            name: mssql-server-conf
        - name: mssql-tls
          secret:
            secretName: mssql-cert
            items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt
      serviceAccountName: 'mssql-account'
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: mssql
spec:
  selector:
    app: mssql
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  type: ClusterIP
