#
# Persistent Volume
#
#apiVersion: storage.k8s.io/v1
#kind: StorageClass 
#metadata:   
#  name: mssql-storage
#  namespace: mssql
#provisioner: docker.io/hostpath
#---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-data-volume
  namespace: mssql
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/c/My Databases/MSSQL/"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
