apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certifcate
spec:
  secretName: ca-cert
  duration: 3650d
  renewBefore: 15d
  commonName: Internal CA issuer
  isCA: true
  keySize: 2048
  usages:
  - digital signature
  - key encipherment
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: CA-issuer
spec:
  ca:
    secretName: ca-cert



