apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  namespace: parel25
spec:
  tls:
    - hosts:
        - "*.parel25.nl"
      secretName: wildcard
  rules:
    - host: rabbitmq.parel25.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
  ingressClassName: nginx
