apiVersion: v1
kind: Secret
metadata:
  name: wso2is-keystore
  namespace: parel25
type: Opaque
data:
  PASSWORD: 'd3NvMmNhcmJvbg=='

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wso2is-certificate
  namespace: parel25
spec:
  secretName: wso2is-certificate
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: RSA
    size: 4096
  usages:
    - digital signature
    - key encipherment
    - server auth
  commonName: "is.parel25.nl"
  dnsNames:
    - "is.parel25.nl"
    - "is.parel25.svc.cluster.local"
    - "localhost"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  keystores:
    jks:
      create: true
      passwordSecretRef: # Password used to encrypt the keystore
        key: PASSWORD
        name: wso2is-keystore
    pkcs12:
      create: true
      passwordSecretRef: # Password used to encrypt the keystore
        key: PASSWORD
        name: wso2is-keystore
