apiVersion: v1
kind: Secret
metadata:
  name: wso2is-secret
  namespace: wso2is
type: Opaque
data:
  MSSQL_SERVER: 'bXNzcWwtc2VydmljZS5tc3NxbC5zdmMuY2x1c3Rlci5sb2NhbA=='
  MSSQL_SA_PASSWORD: 'WXJ5NGszeCEzNjQ4YWgyNGE='
