apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <REDACTED>
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
    - dns01:
        azureDNS:
          clientID: <REDACTED>
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: <REDACTED>
          tenantID: <REDACTED>
          resourceGroupName: <REDACTED>
          hostedZoneName: <REDACTED>
          environment: AzurePublicCloud
