apiVersion: v1
kind: Secret
metadata:
  name: azuredns-config
  namespace: cert-manager
type: Opaque
data:
  client-secret: cjFUOFF+S3V5NHJmYnlweWJCZS1ZTV8wcDV6cGdINjZkSkJYMGFCTQo=
  
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bert.moorthaemer@gmail.com
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
    - dns01:
        azureDNS:
          clientID: '2d2001a5-000e-41c9-b730-e6296acdfb85'
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: '1aaadc54-ba26-4acc-9ac6-ac1e43a1664c'
          tenantID: 'a4a8edd7-6215-46f9-a1b0-e267e20c88c6'
          resourceGroupName: 'parel25-rg'
          hostedZoneName: 'parel25.nl'
          environment: AzurePublicCloud
