apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: '$$NAMESPACE$$'
spec:
  secretName: wildcard
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: '*.<your domain>'
  dnsNames:
    - '<your domain>'
    - '*.<your domain>'
