apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: parel25
spec:
  secretName: wildcard
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: "*.parel25.nl"
  subject:
    organizations:
      - AmorWorx 
    organizationalUnits:
      - HQ
    countries:
      - NL
    provinces:
      - Utrecht
    localities:
      - WILNIS
  dnsNames:
    - "parel25.nl"
    - "*.parel25.nl"
